// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdyfzuitnvymwpzdqlvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkeWZ6dWl0bnZ5bXdwemRxbHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTM2NTUsImV4cCI6MjA2NjIyOTY1NX0.3sejCEnTRIgdmu7-F-Nu09vOu8uioWObi1OgPC6e0EY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);